### ISSUE TITLE
Can't run (json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0))

### ISSUE THREAD

**Issue by battlezone100** [Gab0/japonicus#1]
I am trying to get this to work but so far without luck. I found out that this requires Python3 and I've installed DEAR via pip. I've tried this on both a Raspberry pi and a Ubuntu Server.

This is the output of the Ubuntu Server:
`$ python3 evolution.py 
using candlestick dataset {'from': 1451675160, 'to': 1503137160}
DEBUG {'MIN_ VALUES': {'thresholds': {'high': 45, 'fibonacci': 0.1, 'persistence': 1, 'up': -0.125, 'down': -1.25, 'low': 10}, 'short': 1, 'long': 10, 'interval': 0, 'signal': 5}}
DEBUG {'MAX_ VALUES': {'thresholds': {'high': 95, 'fibonacci': 1.0, 'persistence': 5, 'up': 1.525, 'down': 0.4, 'low': 60}, 'short': 21, 'long': 43, 'interval': 33, 'signal': 15}}
Loading new date range;
	{'from': '2016-04-24 22:12:45', 'to': '2016-04-27 22:12:45'}
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "evolution.py", line 74, in Evaluate
    Score = runBacktest(Settings, DateRange)
  File "/home/nils/gekkoJaponicus/gekkoWrapper.py", line 91, in runBacktest
    RESULT = REQ.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
"""
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "evolution.py", line 179, in <module>
    GA = gekko_generations()
  File "evolution.py", line 140, in gekko_generations
    fitnesses = parallel.starmap(toolbox.evaluate, to_simulation)
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 268, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

And this is the output of the Pi:
`python3 evolution.py 
using candlestick dataset {'from': 1483747620, 'to': 1491512820}
Loading new date range;
	{'from': '2017-01-25 17:47:26', 'to': '2017-01-28 17:47:26'}
Traceback (most recent call last):
  File "evolution.py", line 205, in <module>
    GA = gekko_generations()
  File "evolution.py", line 167, in gekko_generations
    fitnesses = toolbox.map(toolbox.evaluate, individues_to_simulate)
  File "evolution.py", line 20, in progrBarMap
    result.append(funct(array[w]))
  File "evolution.py", line 111, in Evaluate
    Score = runBacktest(Settings, DateRange)
  File "/home/nils/gekkoJaponicus/gekkoWrapper.py", line 91, in runBacktest
    RESULT = REQ.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

The cli which runs Gekko UI outputs the following:
`/home/nils/gekko/plugins/paperTrader/paperTrader.js:14
  this.fee = 1 - (calcConfig['fee' + calcConfig.feeUsing.charAt(0).toUpperCase() + calcConfig.feeUsing.slice(1)] + calcConfig.slippage) / 100;
TypeError: Cannot read property 'charAt' of undefined
    at new PaperTrader (/home/nils/gekko/plugins/paperTrader/paperTrader.js:14:57)
    at load (/home/nils/gekko/core/pluginUtil.js:100:22)
    at /home/nils/gekko/node_modules/async/dist/async.js:1156:9
    at replenish (/home/nils/gekko/node_modules/async/dist/async.js:1030:17)
    at iterateeCallback (/home/nils/gekko/node_modules/async/dist/async.js:1015:17)
    at /home/nils/gekko/node_modules/async/dist/async.js:988:16
    at /home/nils/gekko/node_modules/async/dist/async.js:1158:13
    at load (/home/nils/gekko/core/pluginUtil.js:68:14)
    at /home/nils/gekko/node_modules/async/dist/async.js:1156:9
    at replenish (/home/nils/gekko/node_modules/async/dist/async.js:1030:17)
  xxx POST /api/backtest 500 247ms -
  Error: non-error thrown: Child process has died.
      at Object.onerror (/home/nils/gekko/node_modules/koa/lib/context.js:105:40)
      at process._tickCallback (internal/process/next_tick.js:109:7)`

**Comment by Gab0** [comment]
It had major bugs XD all fixed at last commits. It should work now.
Which python3 is this? I run it on python3.6; don't know about other versions.

**Comment by battlezone100** [comment]
I re-cloned the repo and installed Python3.6, still the same issues though.

**Comment by Gab0** [comment]
Both errors are the same, related to response.json() method. Thats related to the communication to gekko api.
So the script now bypasses this method.. it may work now :]
If it still doesn't, could you print the variable Request.text here for me? It's on gekkoWrapper.py line 21.

**Comment by Teecolz** [comment]
I'm getting a similar error, my first Request.text is fine but the second one returns an Internal Server Error. As far as I know, there are no errors in my gekkoWrapper.py as far as paths and URLs go and my config.js is configured accordingly to the IP of the node server. My gekko server is not set to run headless. Using python 3.

I get the same `json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`
My gekko process then prints out the following:
```
  xxx POST /api/backtest 500 450ms -
  Error: non-error thrown: Child process has died.
      at Object.onerror (/Users/me/Documents/gekko/node_modules/koa/lib/context.js:105:40)
      at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by Gab0** [comment]
@Teecolz I'm working on this now... is your dataset from Poloniex (and USD/BTC)?

**Comment by Teecolz** [comment]
@Gab0 Awesome, so far I've been using Poloniex BTC/ZEC (and I've changed `gekkoWrapper.py` accordingly).

**Comment by HOllarves** [comment]
I'm having this issue as well. Could it be realted to the use of talib indicators? Getting no output from gekko process.

**Comment by HOllarves** [comment]
Locale1
first unevaluated: 30
0 individues removed due to equality
[30]
Error: config failure
http://localhost:3000/api/backtest
{'gekkoConfig': {'debug': False, 'info': False, 'watch': {'exchange': 'poloniex', 'currency': 'USDT', 'asset': 'BTC'}, 'paperTrader': {'fee': 0.25, 'feeMaker': 0.15, 'feeTaker': 0.25, 'feeUsing': 'maker', 'slippage': 0.05, 'simulationBalance': {'asset': 1, 'currency': 100}, 'reportRoundtrips': True, 'enabled': True}, 'tradingAdvisor': {'enabled': True, 'method': 'custom', 'candleSize': 30, 'historySize': 10}, 'custom': {'bbparameters': {'optInMAType': 3.56, 'optInNbDevDn': 1.6400000000000001, 'optInNbDevUp': 1.16, 'optInTimePeriod': 2.76}, 'interval': 8.02, 'long': 23.16, 'short': 8.8, 'signal': 6.04, 'stop': 9.260000000000002, 'thresholds': {'down': -0.316, 'high': 73.2, 'low': 18.3, 'persistence': 3.0, 'up': 0.14800000000000002}}, 'backtest': {'daterange': {'from': '2017-10-08 07:30:08', 'to': '2017-12-07 07:30:08'}}, 'performanceAnalyzer': {'riskFreeReturn': 2, 'enabled': True}, 'valid': True}, 'data': {'candleProps': ['id', 'start', 'open', 'high', 'low', 'close', 'vwp', 'volume', 'trades'], 'indicatorResults': True, 'report': True, 'roundtrips': False, 'trades': True}}. Not sure why I am getting a config failure.

**Comment by Gab0** [comment]
@HOllarves last time I tried, TA-Lib worked fine. Can you paste the Gekko side of the error?

**Comment by HOllarves** [comment]
I was recieving a 500 response. The error was very similar to what OP posted in the first place. However, I was able to solve the issue by manually installing talib and tulind libraries using` npm i tulind && npm i talib`. No errors after that, I'm actually trying to solve another bug that happens when attempting to run Japonicus with the custom.js file, as in custom strategy. Might open a new issue if unable to solve what's going on. (Temporary fix for me was simply copying my custom strat into MACD.js and setting my custom config settings under MACD in the settings file, works but it feels so bad.)
